security:
    encoders:
        App\Entity\User:
            algorithm: auto
            
    role_hierarchy:
        ROLE_REVIEWER: ROLE_USER
        ROLE_COMMUNICATION: ROLE_REVIEWER
        ROLE_ADMIN: ROLE_COMMUNICATION

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: logout